apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cart-web
  namespace: ls-pricing-cloudops-test
  labels:
    app: cart-web
    version: v11-scheduling-pressure
  annotations:
    kubernetes.io/change-cause: "fault-11 — scheduling pressure (20 replicas, 500m CPU each — exceeds single-node capacity)"
spec:
  serviceName: cart-web
  replicas: 20
  selector:
    matchLabels:
      app: cart-web
  template:
    metadata:
      labels:
        app: cart-web
    spec:
      containers:
        - name: cart-web
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "500m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
