from __future__ import annotations

import uuid
from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class IncidentStatus(str, Enum):
    PENDING = "pending"
    INVESTIGATING = "investigating"
    RCA_COMPLETE = "rca_complete"
    AWAITING_APPROVAL = "awaiting_approval"  # human must click Approve in Teams
    REMEDIATING = "remediating"
    VALIDATING = "validating"
    RESOLVED = "resolved"
    FAILED = "failed"
    SKIPPED = "skipped"  # human clicked Skip in Teams


class RemediationType(str, Enum):
    ROLLBACK = "rollback"
    RESTART = "restart"
    SCALE = "scale"
    PATCH = "patch"
    SET_IMAGE = "set_image"
    NONE = "none"


class AgentOpinion(BaseModel):
    """Finding from one specialist agent in the Multi-Agent War Room."""
    agent: str                                           # e.g. "SRE Agent"
    icon: str                                            # emoji icon
    color: str = "blue"                                  # UI colour hint
    finding: str                                         # 1-2 sentence summary
    evidence_cited: List[str] = Field(default_factory=list)
    confidence: int                                      # 0-100
    recommendation: str = ""
    concerns: List[str] = Field(default_factory=list)


class AlertPayload(BaseModel):
    service: str
    namespace: str
    message: str
    severity: str = "critical"
    source: str = "manual"


class Evidence(BaseModel):
    pod_status: Optional[str] = None
    pod_logs: Optional[str] = None
    resource_usage: Optional[str] = None
    rollout_history: Optional[str] = None
    deployment_describe: Optional[str] = None
    deployment_info: Optional[dict] = None  # structured data from K8s API (no parsing needed)
    recent_events: Optional[str] = None
    correlated_services: Optional[str] = None  # logs from other failing services in same namespace


class RCAResult(BaseModel):
    root_cause: str                                          # 1-line summary title
    root_cause_points: List[str] = Field(default_factory=list)    # 3-5 evidence-backed findings
    contributing_factors: List[str] = Field(default_factory=list) # secondary factors
    blast_radius: Optional[str] = None                     # downstream impact description
    affected_services: List[str]
    confidence: int
    remediation_type: RemediationType
    remediation_reason: str
    remediation_command: str = ""                           # exact kubectl command generated by AI


class RemediationPlan(BaseModel):
    action: RemediationType
    command: str
    executed: bool = False
    success: Optional[bool] = None
    output: Optional[str] = None


class ValidationResult(BaseModel):
    healthy: bool
    checks_passed: List[str]
    checks_failed: List[str]
    elapsed_seconds: float


class TimelineEvent(BaseModel):
    step: str
    status: str  # "running" | "success" | "error" | "info"
    detail: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class Incident(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid.uuid4())[:8])
    alert: AlertPayload
    status: IncidentStatus = IncidentStatus.PENDING
    evidence: Optional[Evidence] = None
    rca: Optional[RCAResult] = None
    agent_opinions: List[AgentOpinion] = Field(default_factory=list)   # War Room results
    remediation: Optional[RemediationPlan] = None
    validation: Optional[ValidationResult] = None
    postmortem: Optional[str] = None                                   # cached markdown
    started_at: datetime = Field(default_factory=datetime.utcnow)
    resolved_at: Optional[datetime] = None
    total_time_seconds: Optional[float] = None
    timeline: List[TimelineEvent] = Field(default_factory=list)
