"""Remediation executor — runs the AI-generated kubectl command.

No hardcoded playbooks.  The command is generated by either:
  1. The Decision Engine (deterministic patterns with exact commands)
  2. The LLM Judge (dynamic analysis producing exact kubectl commands)

This module just validates the command is safe and executes it.
"""
from __future__ import annotations

import asyncio
import logging
import re
import shlex
import subprocess

import json


import time


from backend.config import settings
from backend.models.incident import RemediationPlan, RemediationType, RCAResult, TimelineEvent

logger = logging.getLogger(__name__)


def _repair_patch_json(cmd: str) -> str:
    """Fix common JSON errors in kubectl patch commands generated by LLMs.

    Handles:
      - Unquoted resource values like 500m, 256Mi → "500m", "256Mi"
      - Wrong nesting like resources.cpu.requests → resources.requests.cpu
      - Trailing commas, missing braces
      - Dotted key paths like "spec.template.spec.containers[0].resources.requests.cpu": "500m"
      - Missing outer braces
    """
    # First, detect dotted-path format and rebuild as a proper strategic merge patch
    dot_match = re.search(
        r"""-p\s+['"]?\s*"?(spec\.template\.spec\.containers\[0\]\.resources\.)""",
        cmd,
    )
    if dot_match:
        # Extract resource values from dotted-path format
        return _rebuild_patch_from_dotted(cmd)

    # Extract the JSON payload from -p '...' or -p "..."
    m = re.search(r"""-p\s+(['"])(.*?)\1\s*$""", cmd, re.DOTALL)
    if not m:
        # Try without quotes: -p {....}
        m = re.search(r"-p\s+(\{.*\})\s*$", cmd, re.DOTALL)
        if not m:
            return cmd
        quote_char = "'"
        json_str = m.group(1)
        prefix = cmd[:m.start(1)]
    else:
        quote_char = m.group(1)
        json_str = m.group(2)
        prefix = cmd[:m.start(1)]

    # Fix unquoted resource values: 500m, 256Mi, 1Gi, 100, etc.
    json_str = re.sub(
        r':\s*(\d+(?:[mMkKGgTt]i?)?)\s*([,}\]])',
        r': "\1"\2',
        json_str,
    )
    json_str = re.sub(
        r':\s*(\d+(?:[mMkKGgTt]i?)?)\s*$',
        r': "\1"',
        json_str,
    )

    # Remove trailing commas before } or ]
    json_str = re.sub(r',\s*([}\]])', r'\1', json_str)

    # Try to parse; if it works, re-serialize cleanly
    try:
        parsed = json.loads(json_str)
        parsed = _fix_resource_nesting(parsed)
        # Ensure proper spec.template.spec.containers nesting for strategic merge
        parsed = _ensure_strategic_merge_structure(parsed)
        clean_json = json.dumps(parsed, separators=(',', ':'))
        return f"{prefix}'{clean_json}'"
    except json.JSONDecodeError:
        return f"{prefix}{quote_char}{json_str}{quote_char}"


def _rebuild_patch_from_dotted(cmd: str) -> str:
    """Rebuild a kubectl patch command from dotted-path format into proper strategic merge JSON.

    Input:  kubectl patch ... -p '"spec.template.spec.containers[0].resources.requests.cpu": "500m"'
    Output: kubectl patch ... -p '{"spec":{"template":{"spec":{"containers":[{"name":"<name>","resources":{"requests":{"cpu":"500m"}}}]}}}}'
    """
    # Extract everything before -p
    prefix_match = re.match(r"(.*?-p)\s+", cmd)
    if not prefix_match:
        return cmd
    prefix = prefix_match.group(1)

    # Extract container name from the command
    name_match = re.search(r"(?:deployment|statefulset)/(\S+)", cmd)
    container_name = name_match.group(1) if name_match else "unknown"

    # Extract all resource key-value pairs
    resources = {"requests": {}, "limits": {}}
    for m in re.finditer(
        r'resources\.(requests|limits)\.(cpu|memory)["\s:]+["\s]*(\d+\w*)',
        cmd,
    ):
        resources[m.group(1)][m.group(2)] = m.group(3)

    if not any(resources.values()):
        return cmd

    # Build clean resource dict
    res_dict = {}
    for category in ("requests", "limits"):
        if resources[category]:
            res_dict[category] = resources[category]

    patch = {
        "spec": {
            "template": {
                "spec": {
                    "containers": [{
                        "name": container_name,
                        "resources": res_dict,
                    }]
                }
            }
        }
    }
    clean_json = json.dumps(patch, separators=(',', ':'))
    return f"{prefix} '{clean_json}'"


def _ensure_strategic_merge_structure(obj: dict) -> dict:
    """Ensure the patch has proper spec.template.spec.containers nesting.

    If the top-level key is 'spec' with 'containers' directly inside,
    wrap in spec.template.spec.containers.
    """
    if "spec" in obj and "containers" in obj["spec"]:
        # Missing template.spec wrapper
        return {"spec": {"template": {"spec": obj["spec"]}}}
    return obj


def _validate_patch_json(cmd: str, service: str) -> str:
    """Verify the -p JSON in a patch command is valid. If not, attempt to extract
    resource values and rebuild a correct command."""
    p_match = re.search(r"""-p\s+['"](.+?)['"]\s*$""", cmd, re.DOTALL)
    if not p_match:
        p_match = re.search(r"-p\s+(\{.+\})\s*$", cmd, re.DOTALL)
    if not p_match:
        return cmd

    json_str = p_match.group(1)
    try:
        json.loads(json_str)
        return cmd  # Valid JSON, no fix needed
    except json.JSONDecodeError:
        pass

    # JSON is broken — extract resource values from anywhere in the command
    logger.warning("Patch JSON is invalid, attempting rebuild: %s", json_str[:200])
    cpu_vals = re.findall(r'(?:cpu)["\s:]+["\s]*(\d+m?)\b', cmd)
    mem_vals = re.findall(r'(?:memory)["\s:]+["\s]*(\d+[MmGgKk]i?)\b', cmd)

    if not cpu_vals and not mem_vals:
        return cmd  # Nothing to extract, let it fail with a clear error

    # Determine if these are requests or limits based on context
    resources = {}
    has_requests = "requests" in cmd.lower()
    has_limits = "limits" in cmd.lower()

    if cpu_vals:
        if has_limits:
            resources.setdefault("limits", {})["cpu"] = cpu_vals[0]
        if has_requests and len(cpu_vals) > 1:
            resources.setdefault("requests", {})["cpu"] = cpu_vals[-1]
        elif has_requests:
            resources.setdefault("requests", {})["cpu"] = cpu_vals[0]
        if not has_limits and not has_requests:
            resources.setdefault("limits", {})["cpu"] = cpu_vals[0]

    if mem_vals:
        if has_limits:
            resources.setdefault("limits", {})["memory"] = mem_vals[0]
        if has_requests and len(mem_vals) > 1:
            resources.setdefault("requests", {})["memory"] = mem_vals[-1]
        elif has_requests:
            resources.setdefault("requests", {})["memory"] = mem_vals[0]
        if not has_limits and not has_requests:
            resources.setdefault("limits", {})["memory"] = mem_vals[0]

    patch = {
        "spec": {
            "template": {
                "spec": {
                    "containers": [{
                        "name": service,
                        "resources": resources,
                    }]
                }
            }
        }
    }
    clean_json = json.dumps(patch, separators=(',', ':'))

    # Rebuild command prefix (everything before -p)
    prefix = cmd[:cmd.index("-p")]
    rebuilt = f"{prefix}-p '{clean_json}'"
    logger.info("Rebuilt patch command: %s", rebuilt)
    return rebuilt


def _fix_resource_nesting(obj):
    """Recursively fix wrong resource nesting patterns.

    LLMs sometimes produce: resources: { cpu: { requests: "X", limits: "Y" } }
    Correct form:            resources: { requests: { cpu: "X" }, limits: { cpu: "Y" } }
    """
    if not isinstance(obj, dict):
        if isinstance(obj, list):
            return [_fix_resource_nesting(item) for item in obj]
        return obj

    result = {}
    for key, value in obj.items():
        if key == "resources" and isinstance(value, dict):
            # Check for wrong nesting: keys are "cpu"/"memory" with dict values containing "requests"/"limits"
            resource_types = {"cpu", "memory"}
            limit_types = {"requests", "limits"}
            if set(value.keys()) & resource_types and all(
                isinstance(v, dict) and set(v.keys()) & limit_types
                for v in value.values()
                if isinstance(v, dict)
            ):
                # Restructure: { cpu: { requests: X, limits: Y }, memory: {...} }
                # → { requests: { cpu: X, memory: ... }, limits: { cpu: Y, memory: ... } }
                fixed = {}
                for res_type in resource_types:
                    if res_type in value and isinstance(value[res_type], dict):
                        for lim_type in limit_types:
                            if lim_type in value[res_type]:
                                fixed.setdefault(lim_type, {})[res_type] = value[res_type][lim_type]
                result[key] = fixed if fixed else _fix_resource_nesting(value)
            else:
                result[key] = _fix_resource_nesting(value)
        else:
            result[key] = _fix_resource_nesting(value)
    return result

def _convert_patch_to_set_resources(cmd: str, service: str) -> str | None:
    """Convert a kubectl patch resource command to kubectl set resources.

    Extracts resource values from the patch JSON (or broken JSON) and builds
    a clean kubectl set resources command — no JSON, no quoting issues.
    Returns None if the command isn't a resource patch.
    """
    # Extract workload name and namespace
    deploy_match = re.search(r"(?:deployment|statefulset)/(\S+)", cmd)
    ns_match = re.search(r"-n\s+(\S+)", cmd)
    ctx_match = re.search(r"--context\s+(\S+)", cmd)

    if not deploy_match:
        return None

    deploy_name = deploy_match.group(1)
    namespace = ns_match.group(1) if ns_match else "{}"

    # Try to parse the JSON payload first
    limits = {}
    requests = {}

    p_match = re.search(r"""-p\s+['"](.+?)['"]?\s*$""", cmd, re.DOTALL)
    if not p_match:
        p_match = re.search(r"-p\s+(\{.+\})\s*$", cmd, re.DOTALL)

    container_name = service
    if p_match:
        json_str = p_match.group(1)
        try:
            parsed = json.loads(json_str)
            # Navigate to the container resources
            containers = (parsed.get("spec", {}).get("template", {})
                         .get("spec", {}).get("containers", []))
            if containers:
                container_name = containers[0].get("name", service)
                res = containers[0].get("resources", {})
                limits = res.get("limits", {})
                requests = res.get("requests", {})
        except (json.JSONDecodeError, ValueError, AttributeError):
            pass

    # If JSON parsing failed, extract values with regex
    if not limits and not requests:
        # Look for limits
        for m in re.finditer(r'"(cpu|memory)"\s*:\s*"([^"]+)"', cmd):
            # Determine context by looking at nearby text
            start = max(0, m.start() - 50)
            context = cmd[start:m.start()].lower()
            if "limits" in context:
                limits[m.group(1)] = m.group(2)
            elif "requests" in context:
                requests[m.group(1)] = m.group(2)
            else:
                # Default to limits
                limits[m.group(1)] = m.group(2)

    if not limits and not requests:
        return None  # Not a resource patch, can't convert

    # Build the clean command
    # Detect workload kind
    kind_match = re.search(r"(deployment|statefulset)/", cmd)
    kind = kind_match.group(1) if kind_match else "deployment"
    parts = [f"kubectl set resources {kind}/{deploy_name} -n {namespace}"]
    parts.append(f"--containers={container_name}")
    if limits:
        parts.append(f"--limits={','.join(f'{k}={v}' for k, v in limits.items())}")
    if requests:
        parts.append(f"--requests={','.join(f'{k}={v}' for k, v in requests.items())}")
    if ctx_match:
        parts.append(f"--context {ctx_match.group(1)}")

    return " ".join(parts)


# Allowed kubectl verbs — anything not in this list is rejected
_SAFE_VERBS = {"rollout", "patch", "scale", "set", "annotate", "label", "edit",
               "rollout undo", "rollout restart"}

# Blocked patterns — reject commands that could be destructive
_BLOCKED_PATTERNS = [
    r"delete\s+(?:namespace|ns|node|pv|crd)",
    r"--force\s+--grace-period=0",
    r"kubectl\s+exec",
    r"kubectl\s+cp\b",
    r"kubectl\s+proxy",
    r"kubectl\s+port-forward",
]


def _validate_command(cmd: str) -> tuple[bool, str]:
    """Check that the command is a safe kubectl operation.
    Returns (is_safe, reason)."""
    cmd_lower = cmd.strip().lower()

    if not cmd_lower.startswith("kubectl"):
        return False, "Command must start with 'kubectl'"

    # Check for blocked patterns
    for pattern in _BLOCKED_PATTERNS:
        if re.search(pattern, cmd_lower):
            return False, f"Command blocked by safety rule: {pattern}"

    # Extract the verb (first word after kubectl and optional flags)
    parts = cmd_lower.split()
    verb_parts = [p for p in parts[1:] if not p.startswith("-")]
    if not verb_parts:
        return False, "No kubectl verb found"

    verb = verb_parts[0]
    # Allow compound verbs like "rollout undo"
    if verb == "rollout" and len(verb_parts) > 1:
        verb = f"rollout {verb_parts[1]}"

    if verb not in _SAFE_VERBS and verb.split()[0] not in _SAFE_VERBS:
        return False, f"Verb '{verb}' is not in the allowed list: {_SAFE_VERBS}"

    return True, "OK"


def _inject_context(cmd: str) -> str:
    """Ensure the kubectl command uses the configured kube context."""
    if settings.kube_context and "--context" not in cmd:
        # Insert --context right after 'kubectl'
        return cmd.replace("kubectl ", f"kubectl --context {settings.kube_context} ", 1)
    return cmd


async def execute(
    rca: RCAResult,
    service: str,
    namespace: str,
    queue: object,  # duck-typed emit queue
    evidence=None,
    decision_pattern: str = "",
) -> RemediationPlan:

    command = rca.remediation_command

    # Sanitize: strip surrounding quotes, escaped quotes, and newlines the LLM may add
    command = command.strip().strip('"').strip("'")
    command = command.replace('\\"', '"').replace("\\'", "'")
    command = command.replace("\n", " ").replace("\r", "")
    # Collapse multiple spaces
    command = re.sub(r"  +", " ", command).strip()

    # Convert kubectl patch resource commands to kubectl set resources
    # (handles both decision engine and LLM-generated patch commands)
    if "patch" in command and "-p" in command:
        converted = _convert_patch_to_set_resources(command, service)
        if converted:
            command = converted
            logger.info("Converted patch to set resources: %s", command)
        else:
            # Fallback: repair and validate the patch JSON
            command = _repair_patch_json(command)
            command = _validate_patch_json(command, service)
            # Guard: reject commands with obviously truncated JSON
            p_match = re.search(r"""-p\s+['"](.+?)['"]?\s*$""", command, re.DOTALL)
            if p_match:
                payload = p_match.group(1)
                try:
                    json.loads(payload)
                except (json.JSONDecodeError, ValueError):
                    logger.warning("Patch JSON still invalid after repair, rejecting: %s", payload[:200])
                    await queue.put(
                        TimelineEvent(
                            step="Remediation",
                            status="error",
                            detail=f"Remediation command has malformed JSON — cannot safely execute. "
                                   f"The AI-generated patch was truncated or invalid.",
                        )
                    )
                    plan = RemediationPlan(action=rca.remediation_type, command=command)
                    plan.executed = False
                    plan.success = False
                    plan.output = "Patch JSON invalid after repair attempts"
                    return plan

    # Also handle 'kubectl set resources' commands that the LLM might generate directly
    if "set resources" in command:
        # Already in the right format — just validate it has --containers
        if "--containers" not in command:
            command = command.replace("set resources ", f"set resources ", 1)
            # Try to add --containers from context
            command = re.sub(
                r"(set resources (?:deployment|statefulset)/\S+ -n \S+)",
                rf"\1 --containers={service}",
                command,
            )

    # Fill namespace placeholder if the decision engine left one
    if "{}" in command:
        command = command.replace("{}", namespace, 1)

    plan = RemediationPlan(
        action=rca.remediation_type,
        command=command or "No command generated",
    )

    # No command = no action
    if rca.remediation_type == RemediationType.NONE or not command:
        await queue.put(
            TimelineEvent(
                step="Remediation",
                status="info",
                detail="AI did not generate a remediation command.",
            )
        )
        plan.executed = False
        return plan

    # Validate command safety
    is_safe, reason = _validate_command(command)
    if not is_safe:
        msg = f"Command rejected by safety check: {reason}. Command: {command}"
        logger.warning(msg)
        await queue.put(TimelineEvent(step="Remediation", status="error", detail=msg))
        plan.executed = False
        return plan

    # Inject kube context
    command = _inject_context(command)
    plan.command = command

    await queue.put(
        TimelineEvent(
            step="Remediation",
            status="running",
            detail=f"Executing: {command}",
        )
    )

    # Execute the command
    loop = asyncio.get_event_loop()
    success, output = await loop.run_in_executor(None, _run_command, command)

    # StatefulSet post-remediation: delete crashing/unhealthy pods so the
    # controller recreates them with the corrected spec.
    # Applies to rollback, resource patches, and restarts on StatefulSets.
    if success and "statefulset/" in command:
        cleanup_msg = await loop.run_in_executor(
            None, _cleanup_statefulset_pods, service, namespace,
        )
        if cleanup_msg:
            output = f"{output}\n{cleanup_msg}"

    plan.executed = True
    plan.success = success
    plan.output = output

    await queue.put(
        TimelineEvent(
            step="Remediation",
            status="success" if success else "error",
            detail=output,
        )
    )
    return plan


# Shell metacharacters that must never appear in commands
_SHELL_METACHARS = re.compile(r"[;|&`$(){}\\<>!]")  # covers ; | && ` $() etc.


def _cleanup_statefulset_pods(service: str, namespace: str) -> str:
    """Force-delete unhealthy pods after a StatefulSet remediation.

    StatefulSets don't automatically recreate pods when only resource
    limits/requests change (unlike Deployments).  After patching the spec
    we must delete the crashing/unhealthy pods so the controller
    recreates them with the corrected template.
    """
    time.sleep(5)  # wait for spec to propagate

    cmd_base = ["kubectl"]
    if settings.kube_context:
        cmd_base += ["--context", settings.kube_context]

    # Find pods that are not fully ready (check all containers, not just first)
    result = subprocess.run(
        cmd_base + [
            "get", "pods", "-n", namespace,
            "-l", f"app={service}",
            "-o", "jsonpath={range .items[*]}{.metadata.name} {.status.phase} "
                  "{range .status.containerStatuses[*]}{.ready}{','}{end}{'\\n'}{end}",
        ],
        capture_output=True, text=True, timeout=10,
    )
    bad_pods = []
    for line in result.stdout.strip().splitlines():
        parts = line.strip().split()
        if len(parts) < 2:
            continue
        pod_name = parts[0]
        phase = parts[1]
        ready_csv = parts[2] if len(parts) > 2 else ""
        # Pod is bad if: not Running, or any container not ready
        if phase != "Running" or "false" in ready_csv:
            bad_pods.append(pod_name)

    if not bad_pods:
        return ""

    deleted = []
    for pod in bad_pods:
        del_result = subprocess.run(
            cmd_base + ["delete", "pod", pod, "-n", namespace, "--grace-period=0", "--force"],
            capture_output=True, text=True, timeout=15,
        )
        if del_result.returncode == 0:
            deleted.append(pod)
            logger.info("Force-deleted crashing pod %s after StatefulSet rollback", pod)

    if deleted:
        return f"Deleted {len(deleted)} crashing pod(s) for StatefulSet re-creation: {', '.join(deleted)}"
    return ""


def _run_command(command: str) -> tuple[bool, str]:
    """Execute a kubectl command and return (success, output).

    Uses shlex.split + shell=False to prevent shell injection.
    """
    # Final shell injection guard — reject commands with metacharacters
    if _SHELL_METACHARS.search(command):
        logger.warning("Command contains shell metacharacters, rejecting: %s", command[:200])
        return False, "Command rejected: contains unsafe shell metacharacters"

    try:
        logger.info("Executing AI-generated command: %s", command)
        args = shlex.split(command)
        result = subprocess.run(
            args, shell=False,
            capture_output=True, text=True, timeout=60,
        )
        success = result.returncode == 0
        output = result.stdout.strip() if success else result.stderr.strip()
        return success, output or "Command completed (no output)."
    except subprocess.TimeoutExpired:
        return False, "Command timed out after 60s"
    except ValueError as exc:
        return False, f"Command parsing error: {exc}"
    except Exception as exc:  # noqa: BLE001
        return False, f"Command execution error: {exc}"
